### PR TITLE
Pull request adding KiCad templates and updated pinout in regards to issue

### PR DESCRIPTION
**Pull request by jyancat**
I've added a KiCad templates folder with everything formatted correctly, but I recommend modifying the info.html file within the meta folder as it is currently blank, along with the footprint for the FXBeam and outline of the standard PCB. I've also added a mechanical folder where I put all the mechanical drawings under a 2D folder and renamed them for clarity. I would also recommend changing some parts of the readme files for clarity/information, such as saying that the fan connector used is a standard JST SH connector. #6

### CODE REVIEW

**Comment by Seneral** [comment]
Thanks for the templates, is really good start for me.
I've done a few changes to the connector symbol, including switching the # notation to an inverted graphical style, and grouping duplicate pins (so they are automatically connected) while retaining the associations of the GND. Just makes it more usable.
However I don't know if Framework is happy with a) a complete restructure and b) a license change
So I am attaching my modifications to the symbols file
[Expansion_Bay.kicad_sym.zip](https://github.com/FrameworkComputer/ExpansionBay/files/12210728/Expansion_Bay.kicad_sym.zip)
Screenshot_20230731_034130

**Comment by jyancat** [comment]
Just to clarify, the licence was not changed, just properly formatted to show when looking at the overview.

**Comment by Seneral** [comment]
Indeed you are right, unless they plan to add other designs (maybe by third parties) that are with a stricter license or none, then it becomes beneficial to keep them separate.
Either way all I'm trying to say is that leaving that up to the maintainer (as is folder structure) is best, especially if you plan to get an actually important addition (kicad templates) through. Each PR should only have one essential component, and the restructure makes it very hard to integrate - as a reminder, other people are familiar with this structure by now, so unless framework themselves wants to change it, we're better off not doing it

On that note, I'd like you make a different PR with JUST the KiCAD templates. I'd recommend the folder "KiCAD User Designs/Expansion_Bay_Template", somewhat like I did in my repo, works nicely. Then I can PR/push my changes to the template onto your repo (changed and fixed quite some stuff, added Fan connectors, expanded the outline of the board to what I **believe** to be the maximum extent), and we do a PR together. Then later I might make another PR when my Oculink stuff works (though likely only after testing).
License change and restructure belong into an issue I think

**Comment by jyancat** [comment]
Closing due to outdated version.

**Pull request closed without merging**
